### ISSUE TITLE
Headers order

### ISSUE THREAD

**Issue by MortonPNZ** [yifeikong/curl_cffi#28]
Hi there i want to suggest one fix to build better impersonate.
Normal Chrome has a particular headers order : `host;connection;user-agent;accept;accept-encoding;accept-language `  (thats may be old info)
On the other hand, in the current build of the Curl_cffi header orders looks way different from the real chrome, which in my opinion is a huge breach in what we are trying to establish with the impersonate itself.

I'm really bad at C code to be able to fix this myself, but if you have some free time and can look into adding that into lib, it would be really neat of you.

Thanks in advice.

**Comment by yifeikong** [comment]
Just did a few research. Unfortunately, there is no easy fix on my side.

First, it's true that header order can be used to fingerprint a http client. A working example can be found on https://privacycheck.sec.lrz.de/passive/fp_hs/fp_header_signature.php

Then, curl does not support precise control over http header order, see the discussion [here](https://github.com/curl/curl/issues/3282) and [here](https://curl.se/mail/lib-2005-10/0047.html). Although it's on the TODO [list](https://curl.se/docs/todo.html#Rearrange_request_header_order) of the curl project.

curl-impersonate only impersonates tls fingerprint and http2 pseudo header order, not http header order.

Because the upstream project curl_cffi depends on do not support this feature, there is nothing we can add. The best you can do is to open an issue in the curl-impersonate repo.

**Comment by yifeikong** [comment]
Reposted your issue as lwthiker/curl-impersonate#149.

**Comment by yifeikong** [comment]
It turns out that the header order is actually correct. I have created a simple script to test, open the server and use your local chrome and curl_cffi to visit respectively.

Here are the script and the results:

```py
import asyncio


class EchoServerProtocol(asyncio.Protocol):
    def connection_made(self, transport):
        peername = transport.get_extra_info('peername')
        print('Connection from {}'.format(peername))
        self.transport = transport

    def data_received(self, data):
        message = data.decode()
        for line in message.split("\n"):
            print(line)
        # print('Data received: {!r}'.format(message))

        data = b"HTTP/1.1 200 OK\r\nConnection: close\r\n"
        self.transport.write(data)

        print('Close the client socket')
        self.transport.close()


async def main():
    # Get a reference to the event loop as we plan to use
    # low-level APIs.
    loop = asyncio.get_running_loop()

    server = await loop.create_server(
        lambda: EchoServerProtocol(),
        '0.0.0.0', 8888)

    async with server:
        await server.serve_forever()


asyncio.run(main())
```

```
Connection from ('127.0.0.1', 57396)
GET / HTTP/1.1
Host: localhost:8888
Connection: keep-alive
sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
DNT: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: en,zh-CN;q=0.9,zh-TW;q=0.8,zh;q=0.7
Cookie: jenkins-timestamper-offset=-28800000

Connection from ('127.0.0.1', 61000)
GET / HTTP/1.1
Host: localhost:8888
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: AAEAAQAAAAIAAAAAAAMAAAPoAAQAYAAAAAYABAAA
sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```
As you can see, the result is almost the same, except that curl tries to establish a http2 connection by default.
