### ISSUE TITLE
Add Support for Chrome Version 112

### ISSUE THREAD

**Issue by BhardwajAnshul** [yifeikong/curl_cffi#53]
It has come to my attention that Chrome Version 112 has recently been released. In order to ensure compatibility and provide the best user experience, please add support for this new version. Thank you!

**Comment by coletdjnz** [comment]
https://github.com/lwthiker/curl-impersonate/commit/fe90762831b73de4a6f26611e3b1e96afd4e9992 chrome 116 support has been merged upstream

**Comment by yqchilde** [comment]
同样期待增加116

**Comment by yifeikong** [comment]
Actually, the fingerpritns for Chrome 116 was changed. However, the EncryptedClientHello TLS extension was added and MAX_CONCURRENT_STREAMS settings was removed in http2 settings frame in Chrome 117, Besides, a new curve will be added in the comming Chrome 120.

Since curl-impersonate was not updating actively, I've almost fixed these issues in my fork of curl-impersonate. These versions will be supported in curl_cffi in the coming weeks.

**Comment by yifeikong** [comment]
Chrome 116 and 119 was added in `0.6.0b2`.
